### ISSUE TITLE
Where is the directory of features,can you supplement

### ISSUE THREAD

**Issue by xueyongsong** [jasonleaster/FaceDetection#2]

**Comment by jasonleaster** [comment]
I used four different type of Haar Feature and the total amount of the features is a huge number.
I removed the genereated features cache file because I can upload it onto github with the limit of the bandwidth of my network.

You can get the features  by your self with running the program `FaceDetection/trainingAdaBoost.py`

From my perspective, I will recommend you to read all about my source code if you want to know everything about the implementation.

**Comment by xueyongsong** [comment]
Before that,I don't have a careful look at the code. 
Now, I will accept your suggestion.
Thank you.
